###Obtenet todas las tareas
GET http://127.0.0.1:8000/api/tareas/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjJhYWM0MWY3NTA4OGZlOGUwOWEwN2Q0NDRjZmQ2YjhjZTQ4MTJhMzEiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vYXBpLXRhcmVhcy01YjgwYyIsImF1ZCI6ImFwaS10YXJlYXMtNWI4MGMiLCJhdXRoX3RpbWUiOjE3NzI0NTc0NzIsInVzZXJfaWQiOiI5ZzBVeWJuVFllVWhKRld4V1NsbVZxeERDRmcxIiwic3ViIjoiOWcwVXliblRZZVVoSkZXeFdTbG1WcXhEQ0ZnMSIsImlhdCI6MTc3MjQ1NzQ3MiwiZXhwIjoxNzcyNDYxMDcyLCJlbWFpbCI6Im1venVjYWFAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbIm1venVjYWFAZ21haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.oCf64BtWvNvXHbm8r6xj3ODIGJM0hDYTtCMBhXFw1QJNJ1d3DLYhCYtj8cmw5JG_3M-u3faUFCvFlpUnciq_ozieqghLMJK1z_tRLKK6EmFhiWfHSzBKwr1E2NWq1IqJkWPOGUFmSm_msFXmYsDAHOo_9Y6ZLDux06JH4WzZi0OFNBLiS3R6PqJ4GOeWyFAkTbl6BGgpCu6QMkrMgPEsGd2iYObZScmMRYMyEDzYBtge4wOSnQaf3IMvegZt5Jat924jgXqA7xynYFYj-Tf_tt_iZXa5s3fnWzc4AdpO2t9NxpnE8SzWPRXM6mTjDIyvTAGY81Tj8Irq0AIH15Q8KQ

###Crear una nueva tarea (POST)
POST http://127.0.0.1:8000/api/tareas/
Content-Type: application/json

{
    "titulo": "Mi primer tarea API",
    "descripcion": "Probando el desacoplamiento",
    "estado": "Pendiente"
}

###  Actualizar una tarea (REEMPLAZA EL ID)
PUT http://127.0.0.1:8000/api/tareas/fiYZOw0M5PXfLeIWibH7/
Content-Type: application/json

{
    "titulo": "Titulo dos veces",
    "descripcion": "Esta descripcion ha sido actualizada",
    "estado": "En proceso"
}


###  Eliminar una tarea (REEMPLAZA EL ID)
DELETE http://127.0.0.1:8000/api/tareas/ID_DE_LA_TAREA/
Content-Type: application/json

### iniciar sesion para obtener eltoken

POST http://127.0.0.1:8000/api/auth/registro/
Content-Type: application/json

{
    "email" : "mozucaa@gmail.com",
    "password" : "6543210"
}
### iniciar sesion para obtener eltoken

POST http://127.0.0.1:8000/api/auth/login/
Content-Type: application/json

{
    "email" : "mozucaa@gmail.com",
    "password" : "6543210"
}

### iniciar sesion para obtener eltoken

POST http://127.0.0.1:8000/api/tareas/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjJhYWM0MWY3NTA4OGZlOGUwOWEwN2Q0NDRjZmQ2YjhjZTQ4MTJhMzEiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vYXBpLXRhcmVhcy01YjgwYyIsImF1ZCI6ImFwaS10YXJlYXMtNWI4MGMiLCJhdXRoX3RpbWUiOjE3NzI0NTc0NzIsInVzZXJfaWQiOiI5ZzBVeWJuVFllVWhKRld4V1NsbVZxeERDRmcxIiwic3ViIjoiOWcwVXliblRZZVVoSkZXeFdTbG1WcXhEQ0ZnMSIsImlhdCI6MTc3MjQ1NzQ3MiwiZXhwIjoxNzcyNDYxMDcyLCJlbWFpbCI6Im1venVjYWFAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbIm1venVjYWFAZ21haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.oCf64BtWvNvXHbm8r6xj3ODIGJM0hDYTtCMBhXFw1QJNJ1d3DLYhCYtj8cmw5JG_3M-u3faUFCvFlpUnciq_ozieqghLMJK1z_tRLKK6EmFhiWfHSzBKwr1E2NWq1IqJkWPOGUFmSm_msFXmYsDAHOo_9Y6ZLDux06JH4WzZi0OFNBLiS3R6PqJ4GOeWyFAkTbl6BGgpCu6QMkrMgPEsGd2iYObZScmMRYMyEDzYBtge4wOSnQaf3IMvegZt5Jat924jgXqA7xynYFYj-Tf_tt_iZXa5s3fnWzc4AdpO2t9NxpnE8SzWPRXM6mTjDIyvTAGY81Tj8Irq0AIH15Q8KQ

{
    "titulo" : "tarea con api segura",
    "descripcion" : "mi primera tarea usando jwt en firebase"
}

###subir la foto de perfil cloudinary
POST http://127.0.0.1:8000/api/perfil/foto/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjJhYWM0MWY3NTA4OGZlOGUwOWEwN2Q0NDRjZmQ2YjhjZTQ4MTJhMzEiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vYXBpLXRhcmVhcy01YjgwYyIsImF1ZCI6ImFwaS10YXJlYXMtNWI4MGMiLCJhdXRoX3RpbWUiOjE3NzI0NzA0NTIsInVzZXJfaWQiOiI5ZzBVeWJuVFllVWhKRld4V1NsbVZxeERDRmcxIiwic3ViIjoiOWcwVXliblRZZVVoSkZXeFdTbG1WcXhEQ0ZnMSIsImlhdCI6MTc3MjQ3MDQ1MiwiZXhwIjoxNzcyNDc0MDUyLCJlbWFpbCI6Im1venVjYWFAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbIm1venVjYWFAZ21haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.nNFAIEKaN4cPW-Gyyc77yJsimfYI-0tkrUT936mGsn_IAjd9tg3yKJq2Hm9rGXA8WyJvYujQtNXL0IA3FX49yJWz21AMdGskAi9lkh29HYqpXhGgEQgCtBw4xIgwV-OmLq5aWQK-dmM3k5bhFaG29BlZhl7TeRuMLTcFdPS-BXoZLA9njL-ydXmHYNvgUu3vJAu6Ly1yW1ipKEEX1sT3IM3QY8IioMWmUFGHuHeguQFcp9cpnrZo_GluMajz2rWRbk8c1CTnJ4RhX8oar1BSh2cddtP_xZZOmbjZ-YeZ-O_P_KYos-lmO47BOCHqz8Sq0p7iesFBozxai9pYqAM8Cw
Content-Type: multipart/form-data; boundary=MiBoundary

--MiBoundary
Content-Disposition: form-data; name="imagen"; filename="avatar.jpeg"
Content-Type: image/jpeg

< C:\Users\SENA\apiscrhistian\hornet.jpeg
--MiBoundary--