###Obtenet todas las tareas
GET http://127.0.0.1:8000/api/tareas/

###Crear una nueva tarea (POST)

POST http://127.0.0.1:8000/api/tareas/
Content-Type: application/json

{
    "titulo": "Mi primer tarea API",
    "descripcion": "Probando el desacoplamiento",
    "estado": "Pendiente"
}

###  Actualizar una tarea (REEMPLAZA EL ID)
PUT http://127.0.0.1:8000/api/tareas/ID_DE_LA_TAREA/
Content-Type: application/json

{
    "estado": "Completada"
}


###  Eliminar una tarea (REEMPLAZA EL ID)
DELETE http://127.0.0.1:8000/api/tareas/ID_DE_LA_TAREA/
Content-Type: application/json